server:
  port: 9090

spring:
  application:
    name: my-blog-api
  config:
    import:
      - classpath:database-dev.yml
      - classpath:multipart-dev.yml
      - classpath:security-dev.yml
      - classpath:redis-dev.yml

profile:
  active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"